### ISSUE TITLE
Fix flaky tests around `AudioFile#convert`

### ISSUE THREAD

**Issue by robbevp** [accentor/api#655]
Our tests seem to be flaky, due to files disappearing before the test finishes.

```
 Error:
TracksControllerAudioTest#test_should_not_create_transcoded_item_if_it_already_exists:
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/runner/work/api/api/tmp/storage/transcodes/1/28/e7/28e731dc-15f9-4869-ac0e-518bfba6ac13
    app/controllers/tracks_controller.rb:90:in `initialize'
    app/controllers/tracks_controller.rb:90:in `open'
    app/controllers/tracks_controller.rb:90:in `audio_with_file'
    app/controllers/tracks_controller.rb:68:in `audio'
    test/test_helper.rb:58:in `get'
    test/controllers/tracks_controller_test.rb:339:in `block in <class:TracksControllerAudioTest>'

bin/rails test test/controllers/tracks_controller_test.rb:333
```

```
Failure:
CreateTranscodedItemJobTest#test_should_create_a_new_TranscodedItem_with_existing_file [test/jobs/create_transcoded_item_job_test.rb:22]:
Expected path '/home/runner/work/api/api/tmp/storage/transcodes/7/e8/33/e833664a-6a5e-4471-b40a-93a9ca011a31' to exist.

bin/rails test test/jobs/create_transcoded_item_job_test.rb:18
```

**Comment by robbevp** [comment]
See these runs:
* https://github.com/accentor/api/actions/runs/11270586788/job/31341622384
* https://github.com/accentor/api/actions/runs/11258556751/job/31305434509
